vich_uploader:
    db_driver: orm
    mappings:
        uploaded_photos:
            uri_prefix: /photos
            upload_destination: '%kernel.project_dir%/public/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
   
            